cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2013/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2013/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2014/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2014/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2015/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2015/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2016/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2016/ejecucion_gastos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2013/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2013/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2014/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2014/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2015/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2015/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2016/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2016/ejecucion_ingresos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2013/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2013/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2014/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2014/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2015/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2015/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Ayuntamiento\ de\ Arona/2016/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Ayuntamiento\ de\ Arona/2016/pagos.csv 


cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2013/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2013/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2014/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2014/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2015/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2015/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2016/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2016/ejecucion_gastos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2013/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2013/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2014/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2014/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2015/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2015/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2016/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2016/ejecucion_ingresos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2013/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2013/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2014/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2014/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2015/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2015/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Cultura/2016/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Cultura/2016/pagos.csv 


cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2013/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2013/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2014/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2014/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2015/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2015/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2016/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2016/ejecucion_gastos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2013/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2013/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2014/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2014/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2015/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2015/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2016/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2016/ejecucion_ingresos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2013/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2013/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2014/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2014/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2015/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2015/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Deportes/2016/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Deportes/2016/pagos.csv 


cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2013/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2013/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2014/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2014/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2015/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2015/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2016/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2016/ejecucion_gastos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2013/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2013/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2014/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2014/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2015/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2015/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2016/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2016/ejecucion_ingresos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2013/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2013/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2014/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2014/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2015/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2015/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Turismo/2016/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Turismo/2016/pagos.csv 


cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/ejecucion_gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/gastos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/gastos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/ejecucion_gastos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/ejecucion_ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/ingresos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/ingresos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/ejecucion_ingresos.csv 

cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2013/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2014/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2015/pagos.csv 
cp /Users/David/Box\ Sync/Civio/Proyectos/13\ Transparencia\ Municipal/Ganados/Arona/02\ Datos/csv/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/pagos.csv /Users/David/src/presupuesto/presupuesto-arona/data/es/municipio/Patronato\ Municipal\ de\ Servicios\ Sociales/2016/pagos.csv 
