python ../manage.py load_budget 2013-2016 municipio "Ayuntamiento de Arona"
python ../manage.py load_budget 2013-2016 municipio "Patronato Municipal de Cultura"
python ../manage.py load_budget 2013-2016 municipio "Patronato Municipal de Deportes"
python ../manage.py load_budget 2013-2016 municipio "Patronato Municipal de Turismo"
python ../manage.py load_budget 2013-2016 municipio "Patronato Municipal de Servicios Sociales"
